POST http://localhost:3000/startup/save
Content-Type: application/json

{

    "userid":"60c46d8408d6da3541a667e3",
    "cin":"44444",
    "pan":"7855555555",
    "startup_name":"FundingKart",
    "founder_name":"Raghul",
    "cofounder_name":"Kumar",
    "company_email":"fundings@google.com",
    "founder_email":"raghul@google.com",
    "cofounder_email":"kumar@google.com",

    "investment_need":"Startup ",
    "founder_aadhar_number":"314313113",
    "founder_pan_number":"444422143",
    "co_founder_aadhar_number":"6839334",
    "co_founder_pan_number":"gjdnsjdf",
    "gst_number":"e4t543",
    "dipp_number":"444473443",
    "udyan_number":"4587411",
    "office_address":"Gandhi nagar, Delhi",
    "incorporation_date":"12/02/2020",
    "ac_no":"4785222222",
    "ifsc":"F467SFG",
    "name":"Rahul",
    "bank_name":"Axis bank",
    
    "documents":[
        {
            "name":"Incorporation Certificates",
            "url":""
        },
        {
            "name":"PAN",
            "url":""
        },
        {
            "name":"AOA",
            "url":""
        }
    ],
    "startup_size":50,
    "about_startup":"This is a web based company",
    "startup_stage":"stage 1",
    "already_funded":true

}

###
GET http://localhost:3000/startup/alldata

###

GET http://localhost:3000/user/check?user_id=60c48027134ee243f0c0007&user_type=

###



GET http://localhost:3000/user/allusers?name=kum

###

POST http://localhost:3000/user/login?email=abc@google.com&password=kumar

###
POST http://localhost:3000/user/forgetpass?email=abc@google.com&newpassword=kumar&oldpassword=password


###

GET http://ascentwebdevelopments.web.app/
###

POST http://localhost:3000/user/update
Content-Type: application/json

{
    "_id": "60c48027134ee243f0c07007",
    "name": "fundkart"
   
}

### 



POST http://localhost:3000/user/signup
Content-Type: application/json

{

"name":"fundkart",
"phone":"785413685",
"email":"fundings@google.com",
"user_type":"startup",
"password":"kumaresh",
"profile_pic":"",
"cover_pic":""


}


###

GET http://localhost:3000/govtorg/search?id=44587777

###

POST http://localhost:3000/govtorg/save
Content-Type: application/json

{

"userid":"44587777",
"logo":"https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Aadhaar_Logo.svg/1200px-Aadhaar_Logo.svg.png",
"department_name":"E-Aadhar",
"about_us":"We update aadhar data",
"facility_we_provide":"updation of user data in Aadhar"

}

###

POST http://localhost:3000/investor/save
Content-Type: application/json

{

"userid":"111",
"aadhar_card":"47855222",
"pan_card":"HB789523N",
"investment_size":2,
"investment_industry":"Paper Industry",
"documents":[

  {
            "name":"Aadhar Card",
            "url":""
        },
{
            "name":"Pan Card",
            "url":""
        }
      

],
"about":"We create papers for Govt Documents"

}

###
POST http://localhost:3000/btools/save
Content-Type: application/json

{

"image":"https://ia-exp1.licdn.com/dms/image/C510BAQFK5UBrIGn7Ng/company-logo_200_200/0/1585224674272?e=2159024400&v=beta&t=55IYXCELlTuGTPrwl-FHrjtaHk-k8kzZ7VHipYDPz6Y",
"body":"https://webdriver.in/",
"title":"Apps  websites"


}

###
POST http://localhost:3000/btools/search
Content-Type: application/json

{
"title":"Free HR Solutions"


}
###

GET http://localhost:3000/btools/alldata

###

POST http://localhost:3000/btools/delete?id=60d2dee91b41db2a775c311d



###


POST http://localhost:3000/govtorg/update
Content-Type: application/json

{

       "_id": "60c6fda90cb27025540501db",
       "department_name":"EAadhar update"
  
}

### 


###


POST http://localhost:3000/investor/update
Content-Type: application/json

{
   "_id": "60c702e503181028e00783d5",
            "userid": "hsgj23"  
}

### 

###


POST http://localhost:3000/startup/update
Content-Type: application/json

{
    "_id": "60c482decc6e130004bd9c53",
    "cin": "SA45357"
   
}

### 
POST http://localhost:3000/news/checknews
Content-Type: application/json

{
   "_id":"60c8410023a57b2410311b5b"
}




###